(()=>{
const _searchDataEvidenceV98=searchDataEvidence;
const _melchiorV98=melchior;
const _balthasarV98=balthasar;
const _casperV98=casper;
const _renderEvidenceV98=renderEvidence;
const _runMagiV98=runMagi;
let lastGenericAnalysis=null;

const norm=s=>String(s??'').normalize('NFKC').replace(/[\s　・･_\-\/()（）\[\]【】]/g,'').toLowerCase();
const num=v=>{const s=String(v??'').replace(/,/g,'').replace(/%$/,'').trim();if(!s||s==='-'||s==='—')return null;const n=Number(s);return Number.isFinite(n)?n:null};
const nfmt=(v,d=3)=>Number.isFinite(v)?v.toFixed(d).replace(/^0(?=\.)/,''):'';
const pct=v=>Number.isFinite(v)?`${(v*100).toFixed(1)}%`:'';
const uniq=a=>[...new Set(a.filter(Boolean))];
const NAME_ALIASES=['選手名','投手名','氏名','名前','選手'];
const DATE_ALIASES=['開催日','試合日','日付','年月日'];
const OPP_ALIASES=['相手校','対戦相手','相手','対戦校'];
const GAME_ALIASES=['試合順','試合','第何試合'];

function colIndex(r,aliases){const cs=r.columns||[];const na=aliases.map(norm);for(let i=0;i<cs.length;i++){const c=norm(cs[i]);if(na.includes(c))return i}for(let i=0;i<cs.length;i++){const c=norm(cs[i]);if(na.some(a=>a&&c.includes(a)))return i}return -1}
function field(r,aliases){const i=colIndex(r,aliases);return i>=0?(r.values||[])[i]:''}
function hasColumn(r,aliases){return colIndex(r,aliases)>=0}
function smartScore(s){const rep=(s.match(/�/g)||[]).length;const jp=(s.match(/[ぁ-んァ-ヶ一-龯々]/g)||[]).length;const known=(s.match(/選手|開催日|打席|打数|安打|投球|守備|相手校|希望/g)||[]).length;return jp+known*18-rep*30}
function decodeBytes(buf){let utf='';try{utf=new TextDecoder('utf-8').decode(buf)}catch(e){}let sj='';try{sj=new TextDecoder('shift_jis').decode(buf)}catch(e){}return smartScore(sj)>smartScore(utf)?sj:utf}
async function responseTextSmart(r){return decodeBytes(await r.arrayBuffer())}

// Drive上のCSV/TXTはShift-JISも自動判別して読み込む。
importDriveFile=async function(id,silent=false){const f=driveIndex.find(x=>x.id===id);if(!f)return 0;try{if(!silent)setDriveState(`${f.name} を読み込み中…`,'ready');dataRecords=dataRecords.filter(r=>!(r.source==='drive'&&r.fileId===id));const before=dataRecords.length,tag=()=>{for(let i=before;i<dataRecords.length;i++)dataRecords[i].fileId=id};if(f.mimeType==='application/vnd.google-apps.spreadsheet'){const r=await driveFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(f.id)}/export?mimeType=application%2Fvnd.openxmlformats-officedocument.spreadsheetml.sheet`);addWorkbookRecords(f.name,await r.arrayBuffer(),'drive')}else if(f.mimeType==='application/vnd.google-apps.document'){const r=await driveFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(f.id)}/export?mimeType=text%2Fplain`);addTextRecords(f.name,await responseTextSmart(r),'drive')}else{const r=await driveFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(f.id)}?alt=media&supportsAllDrives=true`);if(/\.(xls|xlsx|xlsm)$/i.test(f.name)||/spreadsheetml|ms-excel/.test(f.mimeType))addWorkbookRecords(f.name,await r.arrayBuffer(),'drive');else{const text=await responseTextSmart(r);if(/json/i.test(f.mimeType)||/\.json$/i.test(f.name))addJsonRecords(f.name,JSON.parse(text),'drive');else if(/csv/i.test(f.mimeType)||/\.csv$/i.test(f.name))addTableRecords(f.name,'CSV',parseCsv(text),'drive');else addTextRecords(f.name,text,'drive')}}tag();importedDriveFiles.add(f.id);if(!silent){setDriveState(`取込完了：${f.name} ／ ${dataRecords.length-before}行を索引化。`,'ready');renderDriveFiles()}updateRoute();return dataRecords.length-before}catch(err){if(!silent)setDriveState('ファイル取込失敗：'+err.message,'error');throw err}}

// 端末CSVもShift-JISを扱う。既存のUTF-8前提ハンドラより先に処理する。
const localInput=$('localFile');
if(localInput)localInput.addEventListener('change',async e=>{const f=e.target.files&&e.target.files[0];if(!f||!/\.csv$/i.test(f.name))return;e.stopImmediatePropagation();try{const before=dataRecords.length;addTableRecords(f.name,'CSV',parseCsv(decodeBytes(await f.arrayBuffer())),'local');$('localDataState').innerHTML=`端末データ：<b>${escapeHtml(f.name)}</b> から ${dataRecords.length-before}行を索引化`;updateRoute()}catch(err){$('localDataState').textContent='読込失敗：'+err.message}},true);

function domainOf(r){const s=norm(`${r.fileName||''} ${(r.columns||[]).join(' ')}`);if(/希望ポジション/.test(r.fileName||''))return'position';if(/打撃|打席|打数|安打|ops|出塁率|長打率/.test(s))return'batting';if(/投手|投球回|被安打|奪三振|防御率|与四球/.test(s))return'pitching';if(/守備成績|刺殺|補殺|守備率|失策/.test(s))return'fielding';if(/チーム成績|勝敗|得点|失点/.test(s))return'team';return'other'}
function requestedDomains(q){const a=[];if(/打撃|打率|ops|出塁|長打|安打|打点|打席|打数|三振|四球/.test(q))a.push('batting');if(/投手|投球|防御率|whip|奪三振|被安打|失点|自責/.test(q))a.push('pitching');if(/守備成績|失策|守備率|刺殺|補殺/.test(q))a.push('fielding');if(/チーム成績|勝敗|勝率|得点差/.test(q))a.push('team');if(!a.length&&/成績|データ|記録|最近|直近|比較/.test(q))a.push('batting','pitching','fielding');return uniq(a)}
function seasonWanted(q){if(/2026\s*[-–—/]\s*2027|新チーム/.test(q))return'2026-2027';if(/2025\s*[-–—/]\s*2026|旧チーム/.test(q))return'2025-2026';return''}
function playerCandidates(){const out=new Set();for(const r of dataRecords){const i=colIndex(r,NAME_ALIASES);if(i<0)continue;const v=String((r.values||[])[i]??'').trim();if(v&&v.length<=18&&!/選手名|投手名|氏名/.test(v))out.add(v)}return[...out]}
function playerFromQuery(q){const nq=norm(q);return playerCandidates().filter(p=>nq.includes(norm(p))).sort((a,b)=>norm(b).length-norm(a).length)[0]||''}
function rowPlayer(r){return String(field(r,NAME_ALIASES)||'').trim()}
function parseDateValue(v){const s=String(v||'').replace(/\s*[（(].*?[）)]\s*/g,'').trim();const m=s.match(/(20\d{2})[\/.年-](\d{1,2})[\/.月-](\d{1,2})/);if(!m)return 0;return new Date(+m[1],+m[2]-1,+m[3]).getTime()||0}
function gameKey(r){return [field(r,DATE_ALIASES),field(r,OPP_ALIASES),field(r,GAME_ALIASES)].map(x=>String(x||'').trim()).join('|')}
function recentRows(rows,q){if(!/最近|直近/.test(q))return rows;const withDate=rows.map(r=>({r,t:parseDateValue(field(r,DATE_ALIASES)),k:gameKey(r)})).sort((a,b)=>b.t-a.t);const keys=[];for(const x of withDate)if(x.k&&x.k!=='||'&&!keys.includes(x.k)){keys.push(x.k);if(keys.length>=5)break}return keys.length?withDate.filter(x=>keys.includes(x.k)).map(x=>x.r):rows.slice(-30)}
function rowsForDomain(domain,player,season,q){let rows=dataRecords.filter(r=>domainOf(r)===domain);if(season)rows=rows.filter(r=>(r.fileName||'').includes(season)||String(field(r,DATE_ALIASES)||'').includes(season.slice(0,4)));if(player){const np=norm(player);rows=rows.filter(r=>norm(rowPlayer(r))===np||norm((r.values||[]).join(' ')).includes(np))}return recentRows(rows,q)}
function sumField(rows,aliases){let sum=0,seen=0;for(const r of rows){const v=num(field(r,aliases));if(v!==null){sum+=v;seen++}}return seen?sum:null}
function uniqueGames(rows){return new Set(rows.map(gameKey).filter(k=>k&&k!=='||')).size}
function sampleFiles(rows){return uniq(rows.map(r=>r.fileName)).slice(0,6)}
function battingSummary(rows,label){if(!rows.length)return null;const PA=sumField(rows,['打席']),AB=sumField(rows,['打数']),H=sumField(rows,['安打']),RBI=sumField(rows,['打点']),R=sumField(rows,['得点']),B1=sumField(rows,['単打']),B2=sumField(rows,['二塁打']),B3=sumField(rows,['三塁打']),HR=sumField(rows,['本塁打']),SO=sumField(rows,['三振']),BB=sumField(rows,['四球']),HBP=sumField(rows,['死球']),SF=sumField(rows,['犠飛']),SB=sumField(rows,['盗塁']),CS=sumField(rows,['盗塁死']);let hits=H;if(hits===null&&[B1,B2,B3,HR].some(v=>v!==null))hits=(B1||0)+(B2||0)+(B3||0)+(HR||0);const avg=AB?hits/AB:null;const obpDen=(AB||0)+(BB||0)+(HBP||0)+(SF||0),obp=obpDen?((hits||0)+(BB||0)+(HBP||0))/obpDen:null;let singles=B1;if(singles===null&&hits!==null)singles=Math.max(0,hits-(B2||0)-(B3||0)-(HR||0));const tb=AB?((singles||0)+2*(B2||0)+3*(B3||0)+4*(HR||0)):null,slg=AB?tb/AB:null,ops=obp!==null&&slg!==null?obp+slg:null;const parts=[`${label}打撃：${uniqueGames(rows)||rows.length}試合相当`];if(PA!==null)parts.push(`${PA}打席`);if(AB!==null)parts.push(`${AB}打数`);if(hits!==null)parts.push(`${hits}安打`);if(avg!==null)parts.push(`打率${nfmt(avg)}`);if(obp!==null)parts.push(`出塁率${nfmt(obp)}`);if(slg!==null)parts.push(`長打率${nfmt(slg)}`);if(ops!==null)parts.push(`OPS${nfmt(ops)}`);if(RBI!==null)parts.push(`${RBI}打点`);if(R!==null)parts.push(`${R}得点`);if(SO!==null)parts.push(`三振${SO}`);if(BB!==null)parts.push(`四球${BB}`);if(HBP!==null)parts.push(`死球${HBP}`);if(SB!==null)parts.push(`盗塁${SB}`);if(CS!==null&&CS>0)parts.push(`盗塁死${CS}`);return{domain:'batting',text:parts.join('・'),rows,files:sampleFiles(rows)}}
function inningsOuts(v){const s=String(v??'').trim();if(!s)return null;const m=s.match(/^(\d+)(?:\.(\d))?$/);if(!m)return null;const whole=+m[1],frac=m[2]?+m[2]:0;if(frac===1||frac===2)return whole*3+frac;const n=Number(s);return Number.isFinite(n)?Math.round(n*3):null}
function pitchingSummary(rows,label){if(!rows.length)return null;let outs=0,ipSeen=0;for(const r of rows){const o=inningsOuts(field(r,['投球回','投球回数','回']));if(o!==null){outs+=o;ipSeen++}}const H=sumField(rows,['被安打']),K=sumField(rows,['奪三振']),BB=sumField(rows,['与四球','四球']),HBP=sumField(rows,['与死球','死球']),R=sumField(rows,['失点']),ER=sumField(rows,['自責点']),P=sumField(rows,['投球数','球数']),W=sumField(rows,['勝','勝利']),L=sumField(rows,['敗','敗戦']);const ip=outs/3,whip=outs&&H!==null&&BB!==null?((H+BB)/ip):null,kbb=BB!==null&&K!==null&&BB>0?K/BB:null;const ipText=ipSeen?`${Math.floor(outs/3)}.${outs%3}回`:'';const parts=[`${label}投手：${uniqueGames(rows)||rows.length}登板相当`];if(ipText)parts.push(`投球回${ipText}`);if(H!==null)parts.push(`被安打${H}`);if(K!==null)parts.push(`奪三振${K}`);if(BB!==null)parts.push(`与四球${BB}`);if(HBP!==null)parts.push(`与死球${HBP}`);if(R!==null)parts.push(`失点${R}`);if(ER!==null)parts.push(`自責${ER}`);if(P!==null)parts.push(`球数${P}`);if(whip!==null)parts.push(`WHIP${nfmt(whip,2)}`);if(kbb!==null)parts.push(`K/BB${nfmt(kbb,2)}`);if(W!==null&&W>0)parts.push(`勝${W}`);if(L!==null&&L>0)parts.push(`敗${L}`);return{domain:'pitching',text:parts.join('・'),rows,files:sampleFiles(rows)}}
function fieldingSummary(rows,label){if(!rows.length)return null;const E=sumField(rows,['失策','エラー']),PO=sumField(rows,['刺殺']),A=sumField(rows,['補殺']),PB=sumField(rows,['捕逸']),FP=sumField(rows,['守備機会']);const parts=[`${label}守備：${uniqueGames(rows)||rows.length}試合相当`];if(E!==null)parts.push(`失策${E}`);if(PO!==null)parts.push(`刺殺${PO}`);if(A!==null)parts.push(`補殺${A}`);if(PB!==null)parts.push(`捕逸${PB}`);if(FP!==null)parts.push(`守備機会${FP}`);return{domain:'fielding',text:parts.join('・'),rows,files:sampleFiles(rows)}}
function teamSummary(rows,label){if(!rows.length)return null;const R=sumField(rows,['得点']),RA=sumField(rows,['失点']);const parts=[`${label}チーム：${uniqueGames(rows)||rows.length}試合`];if(R!==null)parts.push(`得点${R}`);if(RA!==null)parts.push(`失点${RA}`);if(R!==null&&RA!==null)parts.push(`得失点差${R-RA>=0?'+':''}${R-RA}`);return{domain:'team',text:parts.join('・'),rows,files:sampleFiles(rows)}}
function buildGenericAnalysis(q){if(/希望ポジション/.test(q))return null;const player=playerFromQuery(q),season=seasonWanted(q),domains=requestedDomains(q);if(!domains.length)return null;const label=`${player?player+'の':''}${/最近|直近/.test(q)?'直近':''}`;const sections=[];for(const d of domains){const rows=rowsForDomain(d,player,season,q);const s=d==='batting'?battingSummary(rows,label):d==='pitching'?pitchingSummary(rows,label):d==='fielding'?fieldingSummary(rows,label):d==='team'?teamSummary(rows,label):null;if(s)sections.push(s)}if(!sections.length)return null;const files=uniq(sections.flatMap(s=>s.files)),allRows=uniq(sections.flatMap(s=>s.rows));const summary=sections.map(s=>s.text).join('。');const samples=[];for(const s of sections)for(const r of s.rows.slice(0,4))samples.push(`[${r.fileName}${r.sheetName?' / '+r.sheetName:''}] ${r.display}`);return{player,season,sections,files,rowCount:allRows.length,summary,text:samples.slice(0,12).join('\n')}}

searchDataEvidence=function(q){lastGenericAnalysis=null;const base=_searchDataEvidenceV98(q);if(base&&base.positionAnalysis)return base;const ga=buildGenericAnalysis(q);lastGenericAnalysis=ga;if(!ga)return base;if(base){return{...base,genericAnalysis:ga,count:Math.max(base.count||0,ga.rowCount),files:uniq([...(base.files||[]),...ga.files]),summary:ga.summary,text:`${base.text||''}${base.text?'\n':''}${ga.text}`}}return{count:ga.rowCount,files:ga.files,summary:ga.summary,text:ga.text,genericAnalysis:ga}}

melchior=function(x,evidence){const p=_melchiorV98(x,evidence),g=evidence&&evidence.genericAnalysis;if(!g)return p;p.vote=p.vote==='no'?'no':'cond';p.conf=Math.max(p.conf,88);p.text=`DATA HUBの実データを集計しました。${g.summary}。数字だけで結論を固定せず、対象期間と役割をそろえて判断します。`;p.basis=`${g.summary}。参照：${g.files.join('、')}`;p.concern=`${/最近|直近/.test(x.q)?'直近データは母数が小さくなりやすい点に注意します。':'通算値と直近値を混同しないよう期間を確認します。'} 試合状況や守備負担など、表にない条件は別途確認が必要です。`;return p}
balthasar=function(x){const p=_balthasarV98(x),g=lastGenericAnalysis;if(!g||!x.tacticHits.length)return p;p.conf=Math.max(p.conf,78);p.basis=`戦術判断に使える実データ：${g.summary}`;p.concern=`数値が良くても相手投手・守備位置・投手/捕手兼務・試合展開で最適起用は変わります。固定する場合は解除条件を設定します。`;return p}
casper=function(x){const p=_casperV98(x),g=lastGenericAnalysis;if(!g||!x.humanHits.length)return p;p.conf=Math.max(p.conf,74);p.basis=`実績データは確認できました。${g.player?`${g.player}本人の`:''}役割・成長評価とは分けて扱います。`;p.concern=`成績表だけでは声掛け、責任感、疲労、納得感までは判断できません。数値評価が本人の固定的な評価にならないようにします。`;return p}
renderEvidence=function(e){_renderEvidenceV98(e);if(!e||!e.genericAnalysis)return;const box=$('dataEvidence'),g=e.genericAnalysis;box.classList.add('show');box.innerHTML+=`\n\n<b>【自動集計】</b>\n${escapeHtml(g.summary)}\n<b>【参照ファイル】</b>\n${escapeHtml(g.files.join('、'))}`}
runMagi=function(){_runMagiV98();setTimeout(()=>{if(lastGenericAnalysis&&$('response').classList.contains('show'))$('next').textContent='NEXT：必要なら「直近」「相手校」「打順」「守備位置」など条件を追加して、同じデータを絞り込み比較できます。'},0)}
})();