(async()=>{
  const V='0.10.58', A='168';
  const extras=['/analysis-v093.js?v=140','/generic-v098.js?v=140','/batfix-v100.js?v=140','/role-v101.js?v=140','/pitch-v113.js?v=140','/final-v102.js?v=140','/final-detail-v103.js?v=140','/layout-v112.js?v=140','/desktop-layout-v185.js?v=186','/engine/magi-engine-v1.js?v=187','/drive-evidence-v194.js?v=203','/engine-ui-v187.js?v=194'];
  const load=s=>new Promise(r=>{const x=document.createElement('script');x.src=s;x.onload=r;x.onerror=r;document.head.appendChild(x)});
  const inline=c=>{if(!c||!c.trim())return;const s=document.createElement('script');s.textContent=c;document.body.appendChild(s)};
  const brand=()=>{
    const hero=document.querySelector('.hero'); if(!hero)return;
    if(!document.getElementById('magi-brand-v140-style')){const st=document.createElement('style');st.id='magi-brand-v140-style';st.textContent=`.magiTitleRow{display:flex;align-items:center;gap:8px;margin:8px 0 10px;min-width:0}.magiTitleRow .magiMainTitle{margin:0;flex:0 0 auto;line-height:1;font-size:42px;letter-spacing:.08em}.magiBrandLockup{display:flex;align-items:center;gap:6px;min-width:0}.magiBrandSymbol{width:54px;height:54px;display:block;flex:0 0 auto;object-fit:contain}.magiBrandCopy{min-width:0;line-height:1.18}.magiBrandEn{font-size:11.5px;font-weight:600;color:#dbe7f4;white-space:nowrap}.magiBrandCatch{margin-top:4px;font-size:11px;font-weight:600;color:#dbe7f4;white-space:nowrap}.hero .jp{margin-top:2px}.personaLead{font-size:13px;line-height:1.55;color:#a9bdd0;margin:-2px 0 12px}.personaAxis{display:block;font-size:16px;font-weight:900;margin:2px 0 8px;color:#fff}.pBlue .personaAxis{color:#7eb0ff}.pRed .personaAxis{color:#ff7d8f}.pGreen .personaAxis{color:#67d39d}.personaPortrait{display:block;width:154px;max-width:46%;height:auto;flex:0 0 auto;align-self:flex-start;margin:-20px -4px 0 0;object-fit:contain;filter:drop-shadow(0 8px 14px rgba(0,0,0,.28))}@media(max-width:430px){.magiTitleRow .magiMainTitle{font-size:34px}.magiBrandSymbol{width:46px;height:46px}.magiBrandEn,.magiBrandCatch{font-size:8.7px}.personaPortrait{width:154px;max-width:46%}}`;document.head.appendChild(st)}
    const h1=hero.querySelector('h1');if(!h1)return;h1.classList.add('magiMainTitle');let row=h1.closest('.magiTitleRow');if(!row){row=document.createElement('div');row.className='magiTitleRow';h1.parentNode.insertBefore(row,h1);row.appendChild(h1)}row.querySelectorAll('.magiBrandLockup').forEach(n=>n.remove());const lock=document.createElement('div');lock.className='magiBrandLockup';lock.innerHTML='<img class="magiBrandSymbol" src="/magi-official-symbol-v125.svg?v=140" alt="MAGI"><div class="magiBrandCopy"><div class="magiBrandEn">Maruoka Advanced Game Intelligence</div><div class="magiBrandCatch">知りたいことから、伝えたいことまで。</div></div>';row.appendChild(lock)
  };
  const versions=()=>{const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode())n.nodeValue=n.nodeValue.replace(/v0\.(?:9|10)\.\d+/g,'v'+V);window.MAGI_ACTIVE_VERSION=V};
  try{const r=await fetch('/index-legacy-v092.html?v='+A,{cache:'no-store'});if(!r.ok)throw new Error('legacy '+r.status);const p=new DOMParser().parseFromString(await r.text(),'text/html');const scripts=[...p.querySelectorAll('script')].map(s=>({src:s.getAttribute('src')||'',code:s.textContent||''}));p.querySelectorAll('script').forEach(s=>s.remove());document.title='MAGI Web v'+V;p.head.querySelectorAll('style').forEach(o=>{const s=document.createElement('style');s.textContent=o.textContent;document.head.appendChild(s)});document.body.innerHTML=p.body.innerHTML;for(const s of scripts){if(s.src)await load(s.src);else inline(s.code)}for(const s of extras)await load(s);brand();versions();setTimeout(()=>{brand();versions()},250)}catch(e){document.body.innerHTML='<div style="padding:28px">MAGI v'+V+'の読み込みに失敗しました。<br><small>'+String(e&&e.message||e)+'</small></div>'}
})();